/**
 * v0.5.1 — PowerShell parity tests for per-conv trajectory rotation.
 *
 * Verifies the ace_track_mcp.ps1 script generated by createWindowsHookScripts()
 * matches the bash counterpart's per-conversation routing behavior:
 *   conversation_id present -> .cursor/ace/tasks/<conv_id>/mcp_trajectory.jsonl
 *   conversation_id absent  -> top-level .cursor/ace/mcp_trajectory.jsonl
 *
 * Runs cross-platform via pwsh (PowerShell Core). On macOS, pwsh is installed
 * via `brew install --cask powershell`. Tests are auto-skipped if pwsh is not
 * available. Uses spawnSync (no shell, no command injection risk — input is
 * a literal absolute path the test itself created in os.tmpdir()).
 */

import { describe, it, expect, beforeEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { spawnSync } from 'child_process';
import { ORPHAN_SCRIPTS } from '../../ace/workspaceCleanup';

function hasPwsh(): boolean {
	const r = spawnSync('pwsh', ['--version'], { stdio: 'pipe' });
	return r.status === 0;
}

const describePwsh = hasPwsh() ? describe : describe.skip;

/** The PS1 script body that createWindowsHookScripts() now writes for ace_track_mcp.ps1.
 *  Kept inline so the test never depends on extension activation (vscode API). */
const TRACK_MCP_PS1 = `# ACE MCP Tracking Hook - Captures tool executions for AI-Trail
# Also detects ace_learn calls and extracts task helpfulness (TIME_SAVED)
# Input: tool_name, tool_input, result_json, duration, conversation_id

$inputJson = [Console]::In.ReadToEnd()

$aceDir = ".cursor\\ace"
if (-not (Test-Path $aceDir)) {
    New-Item -ItemType Directory -Path $aceDir -Force | Out-Null
}

# Parse input early so we can use conversation_id for per-conv routing.
try {
    $data = $inputJson | ConvertFrom-Json -ErrorAction SilentlyContinue
    $toolName = if ($data.tool_name) { $data.tool_name } else { "" }
    $convIdForTraj = if ($data.conversation_id) { $data.conversation_id } elseif ($data.conv_id) { $data.conv_id } else { "" }
} catch {
    $toolName = ""
    $convIdForTraj = ""
}

# v0.5.1 per-conv trajectory rotation. Mirror bash ace_track_mcp.sh logic.
if ($convIdForTraj -and $convIdForTraj -ne "null") {
    $perConvDir = "$aceDir\\tasks\\$convIdForTraj"
    if (-not (Test-Path $perConvDir)) {
        New-Item -ItemType Directory -Path $perConvDir -Force | Out-Null
    }
    $inputJson | Out-File -Append -FilePath "$perConvDir\\mcp_trajectory.jsonl" -Encoding utf8
} else {
    $inputJson | Out-File -Append -FilePath "$aceDir\\mcp_trajectory.jsonl" -Encoding utf8
}
`;

function runPs(scriptPath: string, stdin: string, cwd: string): { exitCode: number; stdout: string; stderr: string } {
	const result = spawnSync('pwsh', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', scriptPath], {
		input: stdin,
		cwd,
		encoding: 'utf-8',
		timeout: 10000,
	});
	return {
		exitCode: result.status ?? -1,
		stdout: (result.stdout || '').toString(),
		stderr: (result.stderr || '').toString(),
	};
}

describePwsh('v0.5.1 PowerShell parity — ace_track_mcp.ps1 per-conv routing', () => {
	let tmpDir: string;
	let scriptsDir: string;
	let scriptPath: string;

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ace-ps-perconv-'));
		scriptsDir = path.join(tmpDir, '.cursor', 'scripts');
		fs.mkdirSync(scriptsDir, { recursive: true });
		scriptPath = path.join(scriptsDir, 'ace_track_mcp.ps1');
		fs.writeFileSync(scriptPath, TRACK_MCP_PS1);
	});

	it('writes to per-conv tasks/<conv_id>/mcp_trajectory.jsonl when conversation_id present', () => {
		const convId = 'conv-abc-123';
		const input = JSON.stringify({
			tool_name: 'Read',
			tool_input: { file_path: 'src/foo.ts' },
			conversation_id: convId,
			duration: 42,
		});

		const res = runPs(scriptPath, input, tmpDir);
		expect(res.exitCode).toBe(0);

		const perConvFile = path.join(tmpDir, '.cursor', 'ace', 'tasks', convId, 'mcp_trajectory.jsonl');
		expect(fs.existsSync(perConvFile)).toBe(true);

		const content = fs.readFileSync(perConvFile, 'utf8');
		expect(content).toContain('"tool_name"');
		expect(content).toContain(convId);

		// Top-level file must NOT receive the entry on the per-conv path.
		const topLevel = path.join(tmpDir, '.cursor', 'ace', 'mcp_trajectory.jsonl');
		expect(fs.existsSync(topLevel)).toBe(false);
	});

	it('falls back to top-level mcp_trajectory.jsonl when conversation_id is missing', () => {
		const input = JSON.stringify({
			tool_name: 'Grep',
			tool_input: { pattern: 'foo' },
			duration: 7,
		});

		const res = runPs(scriptPath, input, tmpDir);
		expect(res.exitCode).toBe(0);

		const topLevel = path.join(tmpDir, '.cursor', 'ace', 'mcp_trajectory.jsonl');
		expect(fs.existsSync(topLevel)).toBe(true);
		const content = fs.readFileSync(topLevel, 'utf8');
		expect(content).toContain('"tool_name"');
	});

	it('treats conversation_id="null" string as absent (parity with bash)', () => {
		const input = JSON.stringify({
			tool_name: 'Edit',
			conversation_id: 'null',
		});

		const res = runPs(scriptPath, input, tmpDir);
		expect(res.exitCode).toBe(0);

		const topLevel = path.join(tmpDir, '.cursor', 'ace', 'mcp_trajectory.jsonl');
		expect(fs.existsSync(topLevel)).toBe(true);
	});

	it('does not crash on empty stdin', () => {
		const res = runPs(scriptPath, '', tmpDir);
		expect(res.exitCode).toBe(0);
	});

	it('appends multiple entries to the same per-conv file', () => {
		const convId = 'conv-multi';
		runPs(scriptPath, JSON.stringify({ tool_name: 'Read', conversation_id: convId, n: 1 }), tmpDir);
		runPs(scriptPath, JSON.stringify({ tool_name: 'Read', conversation_id: convId, n: 2 }), tmpDir);

		const perConvFile = path.join(tmpDir, '.cursor', 'ace', 'tasks', convId, 'mcp_trajectory.jsonl');
		const content = fs.readFileSync(perConvFile, 'utf8');
		expect(content).toContain('"n":1');
		expect(content).toContain('"n":2');
	});
});

describe('v0.5.1 ORPHAN_SCRIPTS includes PS1 orphans', () => {
	it('lists the three PS1 track-script orphans for parity with bash', () => {
		expect(ORPHAN_SCRIPTS).toContain('ace_track_edit.ps1');
		expect(ORPHAN_SCRIPTS).toContain('ace_track_response.ps1');
		expect(ORPHAN_SCRIPTS).toContain('ace_track_shell.ps1');
	});

	it('still lists the bash orphans (regression guard)', () => {
		expect(ORPHAN_SCRIPTS).toContain('ace_track_edit.sh');
		expect(ORPHAN_SCRIPTS).toContain('ace_track_response.sh');
		expect(ORPHAN_SCRIPTS).toContain('ace_track_shell.sh');
		expect(ORPHAN_SCRIPTS).toContain('ace_stop_hook.sh.bak');
	});
});
