/**
 * Unit tests for session_id tracking implementation in Cursor extension
 *
 * Tests the correct session_id flow:
 * 1. session_id is generated by ace_search (per-task UUID, NOT conversation_id)
 * 2. AI must remember session_id from ace_search response
 * 3. AI passes session_id to ace_learn after task completion
 * 4. Stop hook only provides AI-Trail summary (does NOT handle session_id)
 *
 * These tests validate both Unix bash and Windows PowerShell script logic.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { spawnSync } from 'child_process';

// Mock vscode module (not available outside VS Code)
vi.mock('vscode', () => ({
	window: {
		showInformationMessage: vi.fn().mockResolvedValue(undefined),
		showWarningMessage: vi.fn().mockResolvedValue(undefined),
		showErrorMessage: vi.fn().mockResolvedValue(undefined),
	},
	workspace: {
		workspaceFolders: [],
		getConfiguration: vi.fn(() => ({
			get: vi.fn(),
		})),
	},
	Uri: {
		joinPath: vi.fn((uri, ...segments) => ({
			fsPath: path.join(uri.fsPath, ...segments),
		})),
	},
}));

describe('Session ID Tracking Implementation', () => {
	// Temporary directory for test files
	let tempDir: string;
	let aceDir: string;
	let scriptsDir: string;

	beforeEach(() => {
		// Create temp directory for test artifacts
		tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ace-session-test-'));
		aceDir = path.join(tempDir, '.cursor', 'ace');
		scriptsDir = path.join(tempDir, '.cursor', 'scripts');
		fs.mkdirSync(aceDir, { recursive: true });
		fs.mkdirSync(scriptsDir, { recursive: true });
	});

	afterEach(() => {
		// Cleanup temp directory
		if (tempDir && fs.existsSync(tempDir)) {
			fs.rmSync(tempDir, { recursive: true, force: true });
		}
	});

	describe('Stop Hook Script Logic (Unix)', () => {
		const isUnix = process.platform !== 'win32';

		it('should extract status and loop_count (NOT conversation_id)', () => {
			if (!isUnix) {
				return; // Skip on Windows
			}

			const testInput = JSON.stringify({
				status: 'completed',
				loop_count: 0,
			});

			// Stop hook only reads status and loop_count
			const statusResult = spawnSync('bash', ['-c', `echo '${testInput}' | jq -r '.status // empty'`], {
				encoding: 'utf-8',
			});

			const loopResult = spawnSync('bash', ['-c', `echo '${testInput}' | jq -r '.loop_count // 0'`], {
				encoding: 'utf-8',
			});

			expect(statusResult.stdout.trim()).toBe('completed');
			expect(loopResult.stdout.trim()).toBe('0');
		});

		it('should log stop event to ace-relevance.jsonl', () => {
			if (!isUnix) {
				return;
			}

			// Stop hook now logs a stop event instead of sending followup_message
			const stopEvent = { event: 'stop', summary: 'MCP:5 Shell:3 Edits:2 Responses:1', git_branch: 'main', git_hash: 'abc123' };

			expect(stopEvent.event).toBe('stop');
			expect(stopEvent.summary).toContain('MCP:');
			expect(stopEvent.git_branch).toBe('main');
		});

		it('should only generate summary on status=completed and loop_count=0', () => {
			if (!isUnix) {
				return;
			}

			// Test condition: should process
			const shouldProcess = (status: string, loopCount: number) => {
				return status === 'completed' && loopCount === 0;
			};

			expect(shouldProcess('completed', 0)).toBe(true);
			expect(shouldProcess('completed', 1)).toBe(false);
			expect(shouldProcess('running', 0)).toBe(false);
			expect(shouldProcess('failed', 0)).toBe(false);
		});
	});

	describe('Stop Hook Script Logic (Windows)', () => {
		// These tests validate PowerShell logic patterns conceptually
		// Actual PowerShell execution only works on Windows

		it('should extract status and loop_count (no conversation_id)', () => {
			// Test the PowerShell logic pattern (conceptual test)
			const testInput = {
				status: 'completed',
				loop_count: 0,
			};

			// Stop hook only reads status and loop_count
			const status = testInput.status;
			const loopCount = testInput.loop_count;

			expect(status).toBe('completed');
			expect(loopCount).toBe(0);
		});

		it('should log stop event to ace-relevance.jsonl for Windows', () => {
			// Stop hook now logs a stop event instead of sending followup_message
			const stopEvent = { event: 'stop', summary: 'MCP:5 Shell:3 Edits:2 Responses:1', git_branch: 'main', git_hash: 'abc123' };

			expect(stopEvent.event).toBe('stop');
			expect(stopEvent.summary).toContain('MCP:');
		});
	});

	describe('Extension Stop Hook Template (Unix)', () => {
		it('should contain status extraction in Unix script template', () => {
			// The Unix stop hook script template from extension.ts
			const unixScriptTemplate = `#!/bin/bash
# ACE Stop Hook - Aggregates trajectory summary on task completion
# Input: status, loop_count, transcript_path, conversation_id

input=$(cat)
status=$(echo "$input" | jq -r '.status // empty')`;

			expect(unixScriptTemplate).toContain('status');
			expect(unixScriptTemplate).toContain('jq -r');
		});

		it('should use hybrid approach: followup_message only when ace_learn not called', () => {
			const unixLogTemplate = `
summary="MCP:$mcp_count Shell:$shell_count Edits:$edit_count Responses:$response_count"
echo "{\\"event\\": \\"stop\\", \\"summary\\": \\"$summary\\"}" >> "$ace_dir/ace-relevance.jsonl"

if [ "$loop_count" = "0" ] && [ ! -f "$ace_dir/ace-review-result.json" ]; then
  msg="Now call ace_learn"
  echo "{\\"followup_message\\": \\"$msg\\"}"
else
  echo '{}'
fi`;

			expect(unixLogTemplate).toContain('ace-relevance.jsonl');
			expect(unixLogTemplate).toContain('ace-review-result.json');
			expect(unixLogTemplate).toContain('followup_message');
			expect(unixLogTemplate).toContain('loop_count');
		});
	});

	describe('Extension Stop Hook Template (Windows)', () => {
		it('should contain status extraction in Windows script template', () => {
			const windowsScriptTemplate = `# ACE Stop Hook - Aggregates trajectory summary on task completion
# Input: status, loop_count, transcript_path, conversation_id

$inputJson = [Console]::In.ReadToEnd()
$data = $inputJson | ConvertFrom-Json -ErrorAction SilentlyContinue
$status = $data.status`;

			expect(windowsScriptTemplate).toContain('$status');
			expect(windowsScriptTemplate).toContain('ConvertFrom-Json');
		});

		it('should use hybrid approach for Windows: followup_message when ace_learn not called', () => {
			const windowsLogTemplate = `
$entry | Out-File -Append -FilePath "$aceDir\\ace-relevance.jsonl" -Encoding utf8

if ($loopCount -eq 0 -and -not (Test-Path "$aceDir\\ace-review-result.json")) {
    $msg = "Now call ace_learn"
    Write-Output "{\`"followup_message\`": \`"$msg\`"}"
} else {
    Write-Output '{}'
}`;

			expect(windowsLogTemplate).toContain('ace-relevance.jsonl');
			expect(windowsLogTemplate).toContain('ace-review-result.json');
			expect(windowsLogTemplate).toContain('followup_message');
			expect(windowsLogTemplate).toContain('loopCount');
		});
	});

	describe('Rules File (ace-patterns/RULE.mdc)', () => {
		it('should instruct AI to use ace_search before tasks', () => {
			const rulesContent = `
## HOW TO USE ace_search

1. **Read the user's task/request**
2. **Call ace_search with the task as query:**
   \`\`\`
   ace_search(query="<user's task description>")
   \`\`\`
3. **Review returned patterns** (5-10 relevant ones)
4. **Apply patterns to implementation**`;

			expect(rulesContent).toContain('ace_search');
			expect(rulesContent).toContain('Review returned patterns');
		});

		it('should instruct to include TIME_SAVED in ace_learn output', () => {
			const rulesContent = `
**IMPORTANT: Include TIME_SAVED on the FIRST LINE of the output field.**

\`\`\`
ace_learn(
  task="<what you accomplished>",
  trajectory=["<key steps>"],
  success=true,
  output="TIME_SAVED: Xm | <one-line reason>\\n<lessons learned>"
)
\`\`\``;

			expect(rulesContent).toContain('TIME_SAVED');
			expect(rulesContent).toContain('ace_learn');
			expect(rulesContent).toContain('output');
		});

		it('should show TIME_SAVED format with minutes and reason', () => {
			const example = 'TIME_SAVED: 15m | Auth patterns avoided OAuth docs research';

			expect(example).toContain('TIME_SAVED:');
			expect(example).toContain('15m');
			expect(example).toContain('|');
		});
	});

	describe('ace_search Response Format', () => {
		it('should return session_id in ace_search response', () => {
			// Mock ace_search response structure
			const aceSearchResponse = {
				results: [
					{ id: 'pattern-1', content: 'Pattern 1', confidence: 0.9 },
					{ id: 'pattern-2', content: 'Pattern 2', confidence: 0.85 },
				],
				session_id: 'uuid-abc-123-def-456',
				count: 2,
			};

			expect(aceSearchResponse).toHaveProperty('session_id');
			expect(aceSearchResponse.session_id).toBeTruthy();
			expect(typeof aceSearchResponse.session_id).toBe('string');
		});
	});

	describe('ace_learn Input Format', () => {
		it('should accept session_id parameter', () => {
			// Mock ace_learn call structure
			const aceLearnCall = {
				task: 'Implement JWT authentication',
				trajectory: ['Step 1', 'Step 2', 'Step 3'],
				success: true,
				output: 'Successfully implemented JWT auth',
				git: {
					commit_hash: 'abc123',
					branch: 'main',
				},
				session_id: 'uuid-abc-123-def-456',
			};

			expect(aceLearnCall).toHaveProperty('session_id');
			expect(aceLearnCall.session_id).toBeTruthy();
			expect(typeof aceLearnCall.session_id).toBe('string');
		});
	});

	describe('Stop Hook Output Format (Hybrid)', () => {
		it('should output followup_message when ace_learn not yet called', () => {
			const output = { followup_message: 'Now call ace_learn to capture what you learned.' };
			const json = JSON.stringify(output);
			const parsed = JSON.parse(json);
			expect(parsed.followup_message).toContain('ace_learn');
		});

		it('should output empty JSON when ace_learn was already called', () => {
			const emptyOutput = '{}';
			const parsed = JSON.parse(emptyOutput);
			expect(Object.keys(parsed).length).toBe(0);
		});

		it('should return empty JSON when not completed', () => {
			const emptyOutput = '{}';
			const parsed = JSON.parse(emptyOutput);
			expect(Object.keys(parsed).length).toBe(0);
		});
	});

	describe('Integration: Full Session Tracking Flow', () => {
		const isUnix = process.platform !== 'win32';

		it('should complete full session tracking flow via afterMCPExecution', () => {
			if (!isUnix) {
				return;
			}

			// Simulate the complete flow:
			// 1. AI calls ace_search
			const aceSearchResponse = {
				results: [],
				session_id: 'integration-test-uuid',
			};
			expect(aceSearchResponse.session_id).toBeTruthy();

			// 2. AI works on the task...

			// 3. AI calls ace_learn with TIME_SAVED in output
			const aceLearnCall = {
				task: 'Test task',
				trajectory: ['Step 1'],
				success: true,
				output: 'TIME_SAVED: 10m | Patterns saved research time\nImportant lesson learned.',
			};

			expect(aceLearnCall.output).toContain('TIME_SAVED:');

			// 4. afterMCPExecution hook detects ace_learn, extracts TIME_SAVED
			const firstLine = aceLearnCall.output.split('\n')[0];
			const match = firstLine.match(/TIME_SAVED:\s*(\S+)\s*\|\s*(.+)/);

			expect(match).toBeTruthy();
			expect(match![1]).toBe('10m');
			expect(match![2]).toContain('Patterns saved');

			// 5. Hook writes ace-review-result.json — extension file watcher flashes status bar
			const reviewResult = {
				helpful_pct: 30, // 10m → 30%
				time_saved: match![1],
				reason: match![2],
			};
			expect(reviewResult.helpful_pct).toBe(30);
		});

		it('should not process when status is not completed', () => {
			const status: string = 'running';

			// Should not generate stop event
			const shouldProcess = status === 'completed';

			expect(shouldProcess).toBe(false);
		});
	});

	describe('Actual Script File Content Verification', () => {
		it('should verify Unix stop hook script uses hybrid approach', () => {
			const projectRoot = path.resolve(__dirname, '../../../..');
			const scriptPath = path.join(projectRoot, '.cursor', 'scripts', 'ace_stop_hook.sh');

			if (fs.existsSync(scriptPath)) {
				const content = fs.readFileSync(scriptPath, 'utf-8');

				expect(content).toContain('status');
				expect(content).toContain('ace-relevance.jsonl');
				expect(content).toContain('ace-review-result.json');
				expect(content).toContain('followup_message');
				expect(content).toContain('loop_count');
				expect(content).not.toContain('ACE_REVIEW');
			}
		});

		it('should verify Unix MCP tracking hook detects ace_learn', () => {
			const projectRoot = path.resolve(__dirname, '../../../..');
			const scriptPath = path.join(projectRoot, '.cursor', 'scripts', 'ace_track_mcp.sh');

			if (fs.existsSync(scriptPath)) {
				const content = fs.readFileSync(scriptPath, 'utf-8');

				expect(content).toContain('ace_learn');
				expect(content).toContain('TIME_SAVED');
				expect(content).toContain('ace-review-result.json');
			}
		});

		it('should verify rules file has TIME_SAVED instructions', () => {
			const projectRoot = path.resolve(__dirname, '../../../..');
			const rulesPath = path.join(projectRoot, '.cursor', 'rules', 'ace-patterns', 'RULE.mdc');

			if (fs.existsSync(rulesPath)) {
				const content = fs.readFileSync(rulesPath, 'utf-8');

				expect(content).toContain('ace_search');
				expect(content).toContain('ace_learn');
				expect(content).toContain('TIME_SAVED');
			}
		});
	});

	describe('Edge Cases', () => {
		it('should handle null session_id in ace_learn', () => {
			const aceLearnCall = {
				task: 'Test',
				trajectory: [],
				success: true,
				output: 'Done',
				git: { commit_hash: 'abc', branch: 'main' },
				session_id: null,
			};

			expect(aceLearnCall.session_id).toBeNull();
			// Server should handle null session_id gracefully
		});

		it('should handle undefined session_id in ace_learn', () => {
			const aceLearnCall: any = {
				task: 'Test',
				trajectory: [],
				success: true,
				output: 'Done',
				git: { commit_hash: 'abc', branch: 'main' },
			};

			expect(aceLearnCall.session_id).toBeUndefined();
			// Server should handle missing session_id gracefully
		});

		it('should handle empty string session_id', () => {
			const aceLearnCall = {
				task: 'Test',
				trajectory: [],
				success: true,
				output: 'Done',
				git: { commit_hash: 'abc', branch: 'main' },
				session_id: '',
			};

			expect(aceLearnCall.session_id).toBe('');
			// Server should handle empty session_id gracefully
		});

		it('should handle special characters in session_id', () => {
			const sessionId = 'session-with-special_chars.123-abc';

			// Should be properly handled in JSON
			const aceLearnCall = {
				session_id: sessionId,
			};

			const json = JSON.stringify(aceLearnCall);
			const parsed = JSON.parse(json);
			expect(parsed.session_id).toBe(sessionId);
		});

		it('should handle very long session_id', () => {
			const sessionId = 'a'.repeat(1000);

			const aceLearnCall = {
				session_id: sessionId,
			};

			expect(aceLearnCall.session_id).toBe(sessionId);
			expect(aceLearnCall.session_id.length).toBe(1000);
		});
	});
});
